### ISSUE TITLE
Bookmarks don't survive page reload

### ISSUE THREAD

**Issue by poVoq** [iquercorb/xows#27]
It seems a bit odd that if I star/favorite a channel it shows up in the sidebar under "bookmarks", but when I reload the page it is gone again from that place.

Also in general it seems like what you call "bookmarks" is not actually a bookmark in the XEP-0402 sense?

I guess what it actually does is this? https://xmpp.org/extensions/xep-0469.html ?

**Comment by iquercorb** [comment]
I implemented Bookmarks as defined in XEP-0402... in a minimalist way. Reviewing the XEP, I see there is an example that show a "pubsub#persist_items" option. I suspect Prosody have this value set to true by default, while Ejabberd set it to false. This could explain what happens to you.

**Comment by poVoq** [comment]
Well, what I mean is that xows seems to use bookmarks via XEP-0402 fine and shows them under the "private channels" heading (even if they are not private), but pressing the star puts them on top of the list under a separate "bookmarks" heading, which seems more like what is described as "pinning" in XEP-0469, no?

**Comment by poVoq** [comment]
Ah, so it uses room discovery to automatically list all channels in the default MUC component? That is a bit uncommon for XMPP clients and should probably be documented somewhere. Typically XMPP clients only list bookmarks.

Is there a way to specify other MUC components to search as well or discourage XOWS to do this (it is probably impossible to use in a large server like conversations.im with hundreds if not thousands of channels on the same component).

**Comment by poVoq** [comment]
I just tested it and the bookmarks still get lost on the latest git master.

**Comment by poVoq** [comment]
This is the initial login (slightly edited to remove PLAIN secrets: 

[initial_login_console-export-2025-8-14_21-34-20.log](https://github.com/user-attachments/files/21780863/initial_login_console-export-2025-8-14_21-34-20.log)

But I don't see it querying any bookmarks.

Setting a bookmark is this log, which seems all correct: 

[setting_bookmark_console-export-2025-8-14_21-43-55.log](https://github.com/user-attachments/files/21780873/setting_bookmark_console-export-2025-8-14_21-43-55.log)

I hope that helps never the less.

**Comment by iquercorb** [comment]
Yep, It might be related, Bookmarks and Avatar are PEP (publish-subscribe) related... It should not forget avatar.

I can also confirm that Room you want to Bookmark is actually NOT public, as specified in its features: `<feature var='muc_hidden'/>`.

Can you open another issue for avatar, with logs when you set avatar from user profile page ?

**Comment by poVoq** [comment]
```
// Client features
    "cli_pepnotify_bkms"  : true,                                 //< Request for Native Bookmarks (XEP-0402) PEP notifications
    "cli_pepnotify_nick"  : true,                                 //< Request for User Nickname (XEP-0172) PEP notifications
    "cli_pepnotify_avat"  : true,                                 //< Request for User Avatar (XEP-0084) PEP notifications
```

Is all true here.

The behavior is a bit different now, but it is not really fixed.

I now get those channels sorted under "public channels" and when I click on them to join, they immediately become a bookmark. But on page reload they are back under "public channels and exhibit the same behavior.

**Comment by iquercorb** [comment]
> I now get those channels sorted under "public channels" and when I click on them to join, they immediately become a bookmark. But on page reload they are back under "public channels" and exhibit the same behavior.

Ok, I understand. Problem is the following : Due to how GUI was designed, I avoided having two instances of the same "Channel" in the list, because user is supposed to join a channel by clicking on it in the list. If there is two instances of the same, this can become a bit confusing. Technically, Bookmarks and Rooms are the same object under the hood, bookmark is a room with a flag that identify it as a bookmark.
So I made the choice to keep public Rooms in the public section even if they are bookmarks, because, the way this is intended to work (the client automatically show list of the public room), there is few advantages of making a bookmark for a room already present in the list.

The best I can do without refactoring everything is to allow the "bookmark" to move from public list to Bookmarks, which become inconstant, since the "public" section is not accurate anymore.

**Comment by poVoq** [comment]
No I am testing with a local channel, but for sure bookmarking a remote channel is something I would want to do.

**Comment by poVoq** [comment]
Ah, I recently changed that for testing. Indeed that is the case and switching it to hidden makes the bookmark option appear again.

**Comment by iquercorb** [comment]
I allowed non-local public room to be bookmarked. Non-local and non-public Room should properly appear as bookmarks. If this is not the case, please open a new issue with console log on bookmark creation and session open.
